events { worker_connections 256; }

http {
    server {
        listen 80;

        # Serve encoded backup file as forced download
        location /files/ {
            alias /usr/share/nginx/files/;
            add_header Content-Disposition 'attachment';
            add_header X-Content-Type-Options nosniff;
            add_header Content-Type 'application/octet-stream';
        }

        # Block everything else
        location / {
            return 403;
        }
    }
}