events { worker_connections 1024; }

http {
    server {
        listen 80;

        # Stage 3: Login portal
        location /novatech-portal/ {
            proxy_pass         http://s3-portal/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        # Stage 4: System Diagnostics & Maintenance Tool
        location /files/ {
            proxy_pass         http://s4-files/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        # Stage 2: API (discoverable by gobuster)
        location /api/ {
            proxy_pass         http://s2-api/api/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        # Stage 1: Default static site
        location / {
            proxy_pass         http://s1-web/;
            proxy_set_header   Host $host;
        }
    }
}